### ISSUE TITLE
Add lockfile check to pnpm check behavior

### ISSUE THREAD

**Issue by finn-orsini** [wayfair/one-version#5]
## Current Behavior

The rule currently only evaluates version specifiers across a workspace. This is sufficient for `yarn` workspaces, but is not for `pnpm`, as described [here](https://github.com/wayfair-incubator/one-version/blob/main/ONE-VERSION.md#pnpm).

`pnpm` workspaces do not have a flat lockfile, so the following is possible: 

```yml
apps/workspace-a:
  specifiers:
     '@wayfair/ui': ^8
  dependencies:
    '@wayfair/ui': 8.0.0_66b146768d72279e63e637aae37792af

apps/workspace-b:
  specifiers:
     '@wayfair/ui': ^8
  dependencies:
    '@wayfair/ui': 8.0.1_b88fe22cf250f8fb4b578ded3c75a78e
```

The rule currently passes in the above scenario.

## Expected Behavior

The check should fail in the above scenario, by checking the lockfile as well as the manifest specifiers.
